### PR TITLE
:whale: (k8s) juice worker's memory

### PR DESCRIPTION
**Pull request by david30907d**
**What does your PR do?**

`person_agg` this DAG (https://github.com/tresl-co/segments-etl/pull/144) would take up so many RAM so juice RAM for each workers

## Checklist

- [ ] Commits are [signed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#sign-your-work)
- [ ] Commits are [squashed](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#squash-commits) (if appropriate)
- [ ] Chart [version bumped](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#versioning)
- [ ] Chart [documentation updated](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#documentation)
- [ ] Passes [linting](https://github.com/airflow-helm/charts/tree/main/CONTRIBUTING.md#linting)

### CODE REVIEW

**Comment by tonyin** [comment]
does this apply to all workers?

is there a flexibility to use different memory for different DAGs?

it's probably minor right now, but it's partially wasteful to use 3g on something simple like import shopify where only 1g would suffice

**Comment by david30907d** [comment]
> does this apply to all workers?
> 
> is there a flexibility to use different memory for different DAGs?
> 
> it's probably minor right now, but it's partially wasteful to use 3g on something simple like import shopify where only 1g would suffice

yea I'm also wondering is it feasible. Would need to consult my ex-coworker and google it also 😄

**Comment by david30907d** [comment]
turns out I need 4Gi for person_agg...

**Comment by tonyin** [comment]
> turns out I need 11Gi for person_agg...
> 
> Screen Shot 2021-04-15 at 3 08 30 PM

some of the memory requirements have already been discovered from running v1 etl, i would look at those as a reference

**Comment by tonyin** [comment]
but if we're running 11gb instances for a simple DAG like import shopify it's kind of wasteful and could get expensive

**Review by tonyin — APPROVED** [review]

**Comment by david30907d** [comment]
@tresl-ryan feel free to leave comments on this PR, even though I've merged it haha

**Pull request merged**
